#!/bin/bash
for kind in "client server terminal"; do
printf "Looking for errors on the $kind..."
find app/$kind -name '*.js' | xargs jshint 2>&1>/dev/null
if [ "$?" == "0" ]; then
    printf '\033[1;32m \xe2\x9c\x94\n\033[0m'; # passed
else
    printf '\033[1;31m \xe2\x9c\x98\n\033[0m'; # failed
    find app/$kind -name '*.js' | xargs jshint # I know it is stupid
                                                # to run again, but it
                                                # happens that I wanna
                                                # show the pretty
                                                # unicode chars before
                                                # that
    exit 1
fi;

done;
